### ISSUE TITLE
Potentially Impossible Quest

### ISSUE THREAD

**Issue by DarianLStephens** [ColonolNutty/CNSurvivalist#37]
For the quest to repair the fuel hatch, you require us to gather Liquid Erchius, but that seems to be impossible without a Matter Manipulator, which comes after this quest.

**Comment by DarianLStephens** [comment]
Is this intentional? Is there some other way to get Liquid Erchius?

**Comment by ColonolNutty** [comment]
Oops, looks like I mistakenly removed the ability for it to collect liquids right from the get go.

**Comment by DarianLStephens** [comment]
Will that even matter if we only get the manipulator after we get the liquid, or can you use the liquid collection without the main manipulator functions?

**Comment by ColonolNutty** [comment]
Hmm, I forgot that I removed the matter manipulator completely. I can't remember, but are there buckets in the game that can be used?

**Comment by ColonolNutty** [comment]
I may just have to change the objective of the quest itself.

**Comment by DarianLStephens** [comment]
I installed the 'Toss That Manipulator' mod recently and stripped down to just the manipulator tools, but there's nothing like that in vanilla.
It might be worth incorporating something like that in to the mod, or as you said, changing the objective.

**Comment by ColonolNutty** [comment]
It will be easier to just create some sort of bucket instead.
